-- Seed arduino state (set to offline initially)
INSERT INTO arduino (port, state) 
VALUES ('/dev/ttyACM0', 'offline')
ON CONFLICT DO NOTHING;

-- Seed current temperature (initial reading)
INSERT INTO current_temperature (current_temp) 
VALUES (-1.0)
ON CONFLICT DO NOTHING;

-- Seed RGB light zones
INSERT INTO rgb_light_vals (name, red, green, blue) VALUES
    ('zone1', 0, 0, 0),  
    ('zone2', 0, 0, 0)     
ON CONFLICT (name) DO NOTHING;

-- seed data for fish_of_the_week
INSERT INTO fish_of_the_week (wiki_url, fish_name) VALUES
    ('https://en.wikipedia.org/wiki/African_lungfish', 'African lungfish'),
    ('https://en.wikipedia.org/wiki/Aholehole', 'Aholehole'),
    ('https://en.wikipedia.org/wiki/Airbreathing_catfish', 'Airbreathing catfish'),
    ('https://en.wikipedia.org/wiki/Airsac_catfish', 'Airsac catfish'),
    ('https://en.wikipedia.org/wiki/Albacore', 'Albacore'),
    ('https://en.wikipedia.org/wiki/Alfonsino', 'Alfonsino'),
    ('https://en.wikipedia.org/wiki/Alligator_gar', 'Alligator gar'),
    ('https://en.wikipedia.org/wiki/Amberjack', 'Amberjack'),
    ('https://en.wikipedia.org/wiki/American_sole', 'American sole'),
    ('https://en.wikipedia.org/wiki/Amur_pike', 'Amur pike'),
    ('https://en.wikipedia.org/wiki/Anchovy', 'Anchovy'),
    ('https://en.wikipedia.org/wiki/Anemonefish', 'Anemonefish'),
    ('https://en.wikipedia.org/wiki/Lophius_piscatorius', 'Lophius piscatorius'),
    ('https://en.wikipedia.org/wiki/Angler_catfish', 'Angler catfish'),
    ('https://en.wikipedia.org/wiki/Antarctic_cod', 'Antarctic cod'),
    ('https://en.wikipedia.org/wiki/Antenna_codlet', 'Antenna codlet'),
    ('https://en.wikipedia.org/wiki/Arapaima', 'Arapaima'),
    ('https://en.wikipedia.org/wiki/Archerfish', 'Archerfish'),
    ('https://en.wikipedia.org/wiki/Arctic_char', 'Arctic char'),
    ('https://en.wikipedia.org/wiki/Armored_gurnard', 'Armored gurnard'),
    ('https://en.wikipedia.org/wiki/Armored_searobin', 'Armored searobin'),
    ('https://en.wikipedia.org/wiki/Armorhead', 'Armorhead'),
    ('https://en.wikipedia.org/wiki/Armorhead_catfish', 'Armorhead catfish'),
    ('https://en.wikipedia.org/wiki/Arowana', 'Arowana'),
    ('https://en.wikipedia.org/wiki/Asiatic_glassfish', 'Asiatic glassfish'),
    ('https://en.wikipedia.org/wiki/Atlantic_bonito', 'Atlantic bonito'),
    ('https://en.wikipedia.org/wiki/Atlantic_cod', 'Atlantic cod'),
    ('https://en.wikipedia.org/wiki/Atlantic_salmon', 'Atlantic salmon'),
    ('https://en.wikipedia.org/wiki/Australian_grayling', 'Australian grayling'),
    ('https://en.wikipedia.org/wiki/Australian_herring', 'Australian herring'),
    ('https://en.wikipedia.org/wiki/Australian_lungfish', 'Australian lungfish'),
    ('https://en.wikipedia.org/wiki/Australian_prowfish', 'Australian prowfish'),
    ('https://en.wikipedia.org/wiki/Bala_shark', 'Bala shark'),
    ('https://en.wikipedia.org/wiki/Ballan_wrasse', 'Ballan wrasse'),
    ('https://en.wikipedia.org/wiki/Bamboo_shark', 'Bamboo shark'),
    ('https://en.wikipedia.org/wiki/Bangus', 'Bangus'),
    ('https://en.wikipedia.org/wiki/Barbus', 'Barbus'),
    ('https://en.wikipedia.org/wiki/Barbus_barbus', 'Barbus barbus'),
    ('https://en.wikipedia.org/wiki/Barbel-less_catfish', 'Barbel-less catfish'),
    ('https://en.wikipedia.org/wiki/Barracuda', 'Barracuda'),
    ('https://en.wikipedia.org/wiki/Barracudina', 'Barracudina'),
    ('https://en.wikipedia.org/wiki/Barramundi', 'Barramundi'),
    ('https://en.wikipedia.org/wiki/Barred_danio', 'Barred danio'),
    ('https://en.wikipedia.org/wiki/Bat_ray', 'Bat ray'),
    ('https://en.wikipedia.org/wiki/Beachsalmon', 'Beachsalmon'),
    ('https://en.wikipedia.org/wiki/Beaked_salmon', 'Beaked salmon'),
    ('https://en.wikipedia.org/wiki/Beluga_sturgeon', 'Beluga sturgeon'),
    ('https://en.wikipedia.org/wiki/Bengal_danio', 'Bengal danio'),
    ('https://en.wikipedia.org/wiki/Betta', 'Betta'),
    ('https://en.wikipedia.org/wiki/Bichir', 'Bichir'),
    ('https://en.wikipedia.org/wiki/Bicolor_goat_fish', 'Bicolor goat fish'),
    ('https://en.wikipedia.org/wiki/Bigeye', 'Bigeye'),
    ('https://en.wikipedia.org/wiki/Bighead_carp', 'Bighead carp'),
    ('https://en.wikipedia.org/wiki/Bigmouth_buffalo', 'Bigmouth buffalo'),
    ('https://en.wikipedia.org/wiki/Istiophoridae', 'Istiophoridae'),
    ('https://en.wikipedia.org/wiki/Black_bass', 'Black bass'),
    ('https://en.wikipedia.org/wiki/Blackfin_Tuna', 'Blackfin Tuna'),
    ('https://en.wikipedia.org/wiki/Black_neon_tetra', 'Black neon tetra'),
    ('https://en.wikipedia.org/wiki/Black_scalyfin', 'Black scalyfin'),
    ('https://en.wikipedia.org/wiki/Black_tetra', 'Black tetra'),
    ('https://en.wikipedia.org/wiki/Black_triggerfish', 'Black triggerfish'),
    ('https://en.wikipedia.org/wiki/Blind_shark', 'Blind shark'),
    ('https://en.wikipedia.org/wiki/Blowfish', 'Blowfish'),
    ('https://en.wikipedia.org/wiki/Blue_catfish', 'Blue catfish'),
    ('https://en.wikipedia.org/wiki/Blue_danio', 'Blue danio'),
    ('https://en.wikipedia.org/wiki/Blue-redstripe_danio', 'Blue-redstripe danio'),
    ('https://en.wikipedia.org/wiki/Bluefish', 'Bluefish'),
    ('https://en.wikipedia.org/wiki/Bluegill', 'Bluegill'),
    ('https://en.wikipedia.org/wiki/Blue_gourami', 'Blue gourami'),
    ('https://en.wikipedia.org/wiki/Blue_whiting', 'Blue whiting'),
    ('https://en.wikipedia.org/wiki/Bluntnose_knifefish', 'Bluntnose knifefish'),
    ('https://en.wikipedia.org/wiki/Bocaccio_rockfish', 'Bocaccio rockfish'),
    ('https://en.wikipedia.org/wiki/Bombay_duck', 'Bombay duck'),
    ('https://en.wikipedia.org/wiki/Bonefish', 'Bonefish'),
    ('https://en.wikipedia.org/wiki/Bonito', 'Bonito'),
    ('https://en.wikipedia.org/wiki/Bonytail', 'Bonytail'),
    ('https://en.wikipedia.org/wiki/Osteoglossoidei', 'Osteoglossoidei'),
    ('https://en.wikipedia.org/wiki/Bowfin', 'Bowfin'),
    ('https://en.wikipedia.org/wiki/Boxfish', 'Boxfish'),
    ('https://en.wikipedia.org/wiki/Bristlenose_catfish', 'Bristlenose catfish'),
    ('https://en.wikipedia.org/wiki/Bronze_corydoras', 'Bronze corydoras'),
    ('https://en.wikipedia.org/wiki/Brook_trout', 'Brook trout'),
    ('https://en.wikipedia.org/wiki/Brown_trout', 'Brown trout'),
    ('https://en.wikipedia.org/wiki/Buffalo_fish', 'Buffalo fish'),
    ('https://en.wikipedia.org/wiki/Bull_trout', 'Bull trout'),
    ('https://en.wikipedia.org/wiki/Burbot', 'Burbot'),
    ('https://en.wikipedia.org/wiki/Bumblebee_goby', 'Bumblebee goby'),
    ('https://en.wikipedia.org/wiki/Japanese_amberjack', 'Japanese amberjack'),
    ('https://en.wikipedia.org/wiki/Burma_danio', 'Burma danio'),
    ('https://en.wikipedia.org/wiki/Pentapodus_nagasakiensis', 'Pentapodus nagasakiensis'),
    ('https://en.wikipedia.org/wiki/Butterfly_ray', 'Butterfly ray'),
    ('https://en.wikipedia.org/wiki/California_halibut', 'California halibut'),
    ('https://en.wikipedia.org/wiki/Canary_rockfish', 'Canary rockfish'),
    ('https://en.wikipedia.org/wiki/Candlefish', 'Candlefish'),
    ('https://en.wikipedia.org/wiki/Cardinalfish', 'Cardinalfish'),
    ('https://en.wikipedia.org/wiki/Cardinal_tetra', 'Cardinal tetra'),
    ('https://en.wikipedia.org/wiki/Carp', 'Carp'),
    ('https://en.wikipedia.org/wiki/Carpsucker', 'Carpsucker'),
    ('https://en.wikipedia.org/wiki/Catla', 'Catla'),
    ('https://en.wikipedia.org/wiki/Cavefish', 'Cavefish'),
    ('https://en.wikipedia.org/wiki/Celebes_rainbowfish', 'Celebes rainbowfish'),
    ('https://en.wikipedia.org/wiki/Central_mudminnow', 'Central mudminnow'),
    ('https://en.wikipedia.org/wiki/Chain_pickerel', 'Chain pickerel'),
    ('https://en.wikipedia.org/wiki/Channel_bass', 'Channel bass'),
    ('https://en.wikipedia.org/wiki/Salvelinus', 'Salvelinus'),
    ('https://en.wikipedia.org/wiki/Chinook_salmon', 'Chinook salmon'),
    ('https://en.wikipedia.org/wiki/Cherubfish', 'Cherubfish'),
    ('https://en.wikipedia.org/wiki/Chub', 'Chub'),
    ('https://en.wikipedia.org/wiki/Chubsucker', 'Chubsucker'),
    ('https://en.wikipedia.org/wiki/Chum_salmon', 'Chum salmon'),
    ('https://en.wikipedia.org/wiki/Cichlid', 'Cichlid'),
    ('https://en.wikipedia.org/wiki/Clingfish', 'Clingfish'),
    ('https://en.wikipedia.org/wiki/Clownfish', 'Clownfish'),
    ('https://en.wikipedia.org/wiki/Clown_loach', 'Clown loach'),
    ('https://en.wikipedia.org/wiki/Clown_triggerfish', 'Clown triggerfish'),
    ('https://en.wikipedia.org/wiki/Cobia', 'Cobia'),
    ('https://en.wikipedia.org/wiki/Coffinfish', 'Coffinfish'),
    ('https://en.wikipedia.org/wiki/Coho_salmon', 'Coho salmon'),
    ('https://en.wikipedia.org/wiki/Collared_carpetshark', 'Collared carpetshark'),
    ('https://en.wikipedia.org/wiki/Collared_dogfish', 'Collared dogfish'),
    ('https://en.wikipedia.org/wiki/Combfish', 'Combfish'),
    ('https://en.wikipedia.org/wiki/Combtail_gourami', 'Combtail gourami'),
    ('https://en.wikipedia.org/wiki/Combtooth_blenny', 'Combtooth blenny'),
    ('https://en.wikipedia.org/wiki/Common_carp', 'Common carp'),
    ('https://en.wikipedia.org/wiki/Common_tunny', 'Common tunny'),
    ('https://en.wikipedia.org/wiki/Convict_blenny', 'Convict blenny'),
    ('https://en.wikipedia.org/wiki/Convict_cichlid', 'Convict cichlid'),
    ('https://en.wikipedia.org/wiki/Cownose_ray', 'Cownose ray'),
    ('https://en.wikipedia.org/wiki/Creek_chub', 'Creek chub'),
    ('https://en.wikipedia.org/wiki/Sciaenidae', 'Sciaenidae'),
    ('https://en.wikipedia.org/wiki/Crocodile_icefish', 'Crocodile icefish'),
    ('https://en.wikipedia.org/wiki/Crucian_carp', 'Crucian carp'),
    ('https://en.wikipedia.org/wiki/Cuckoo_wrasse', 'Cuckoo wrasse'),
    ('https://en.wikipedia.org/wiki/Cusk-eel', 'Cusk-eel'),
    ('https://en.wikipedia.org/wiki/Common_dab', 'Common dab'),
    ('https://en.wikipedia.org/wiki/Damselfish', 'Damselfish'),
    ('https://en.wikipedia.org/wiki/Dartfish', 'Dartfish'),
    ('https://en.wikipedia.org/wiki/Delta_smelt', 'Delta smelt'),
    ('https://en.wikipedia.org/wiki/Denticle_herring', 'Denticle herring'),
    ('https://en.wikipedia.org/wiki/Desert_pupfish', 'Desert pupfish'),
    ('https://en.wikipedia.org/wiki/Devario', 'Devario'),
    ('https://en.wikipedia.org/wiki/Dhufish', 'Dhufish'),
    ('https://en.wikipedia.org/wiki/Dogteeth_tetra', 'Dogteeth tetra'),
    ('https://en.wikipedia.org/wiki/Dojo_loach', 'Dojo loach'),
    ('https://en.wikipedia.org/wiki/Dolly_Varden_trout', 'Dolly Varden trout'),
    ('https://en.wikipedia.org/wiki/Dottyback', 'Dottyback'),
    ('https://en.wikipedia.org/wiki/Dragonet', 'Dragonet'),
    ('https://en.wikipedia.org/wiki/Driftwood_catfish', 'Driftwood catfish'),
    ('https://en.wikipedia.org/wiki/Dusky_grouper', 'Dusky grouper'),
    ('https://en.wikipedia.org/wiki/Dwarf_gourami', 'Dwarf gourami'),
    ('https://en.wikipedia.org/wiki/Dwarf_loach', 'Dwarf loach'),
    ('https://en.wikipedia.org/wiki/Eagle_ray', 'Eagle ray'),
    ('https://en.wikipedia.org/wiki/Eel', 'Eel'),
    ('https://en.wikipedia.org/wiki/Electric_catfish', 'Electric catfish'),
    ('https://en.wikipedia.org/wiki/Electric_eel', 'Electric eel'),
    ('https://en.wikipedia.org/wiki/Electric_knifefish', 'Electric knifefish'),
    ('https://en.wikipedia.org/wiki/Electric_ray', 'Electric ray'),
    ('https://en.wikipedia.org/wiki/Elephantnose_fish', 'Elephantnose fish'),
    ('https://en.wikipedia.org/wiki/Emerald_catfish', 'Emerald catfish'),
    ('https://en.wikipedia.org/wiki/Emperor_angelfish', 'Emperor angelfish'),
    ('https://en.wikipedia.org/wiki/Emperor_bream', 'Emperor bream'),
    ('https://en.wikipedia.org/wiki/Escolar', 'Escolar'),
    ('https://en.wikipedia.org/wiki/Eucla_cod', 'Eucla cod'),
    ('https://en.wikipedia.org/wiki/Eulachon', 'Eulachon'),
    ('https://en.wikipedia.org/wiki/European_chub', 'European chub'),
    ('https://en.wikipedia.org/wiki/European_flounder', 'European flounder'),
    ('https://en.wikipedia.org/wiki/European_minnow', 'European minnow'),
    ('https://en.wikipedia.org/wiki/European_perch', 'European perch'),
    ('https://en.wikipedia.org/wiki/False_trevally', 'False trevally'),
    ('https://en.wikipedia.org/wiki/Fathead_sculpin', 'Fathead sculpin'),
    ('https://en.wikipedia.org/wiki/Featherback', 'Featherback'),
    ('https://en.wikipedia.org/wiki/Fire_goby', 'Fire goby'),
    ('https://en.wikipedia.org/wiki/Filefish', 'Filefish'),
    ('https://en.wikipedia.org/wiki/Fingerfish', 'Fingerfish'),
    ('https://en.wikipedia.org/wiki/Fire_bar_danio', 'Fire bar danio'),
    ('https://en.wikipedia.org/wiki/Flagblenny', 'Flagblenny'),
    ('https://en.wikipedia.org/wiki/Flagfin', 'Flagfin'),
    ('https://en.wikipedia.org/wiki/Flagfish', 'Flagfish'),
    ('https://en.wikipedia.org/wiki/Flathead_catfish', 'Flathead catfish'),
    ('https://en.wikipedia.org/wiki/Flying_gurnard', 'Flying gurnard'),
    ('https://en.wikipedia.org/wiki/French_angelfish', 'French angelfish'),
    ('https://en.wikipedia.org/wiki/Freshwater_hatchetfish', 'Freshwater hatchetfish'),
    ('https://en.wikipedia.org/wiki/Frigate_mackerel', 'Frigate mackerel'),
    ('https://en.wikipedia.org/wiki/Fusilier_fish', 'Fusilier fish'),
    ('https://en.wikipedia.org/wiki/Galjoen_fish', 'Galjoen fish'),
    ('https://en.wikipedia.org/wiki/Gar', 'Gar'),
    ('https://en.wikipedia.org/wiki/Ghost_flathead', 'Ghost flathead'),
    ('https://en.wikipedia.org/wiki/Ghost_shark', 'Ghost shark'),
    ('https://en.wikipedia.org/wiki/Giant_danio', 'Giant danio'),
    ('https://en.wikipedia.org/wiki/Giant_gourami', 'Giant gourami'),
    ('https://en.wikipedia.org/wiki/Giant_sea_bass', 'Giant sea bass'),
    ('https://en.wikipedia.org/wiki/Gila_trout', 'Gila trout'),
    ('https://en.wikipedia.org/wiki/Glowlight_danio', 'Glowlight danio'),
    ('https://en.wikipedia.org/wiki/Goatfish', 'Goatfish'),
    ('https://en.wikipedia.org/wiki/Goby', 'Goby'),
    ('https://en.wikipedia.org/wiki/Golden_dojo', 'Golden dojo'),
    ('https://en.wikipedia.org/wiki/Golden_loach', 'Golden loach'),
    ('https://en.wikipedia.org/wiki/Golden_shiner', 'Golden shiner'),
    ('https://en.wikipedia.org/wiki/Golden_trout', 'Golden trout'),
    ('https://en.wikipedia.org/wiki/Goldeye', 'Goldeye'),
    ('https://en.wikipedia.org/wiki/Goldfish', 'Goldfish'),
    ('https://en.wikipedia.org/wiki/Gombessa', 'Gombessa'),
    ('https://en.wikipedia.org/wiki/Gopher_rockfish', 'Gopher rockfish'),
    ('https://en.wikipedia.org/wiki/Gourami', 'Gourami'),
    ('https://en.wikipedia.org/wiki/Grass_carp', 'Grass carp'),
    ('https://en.wikipedia.org/wiki/Green_swordtail', 'Green swordtail'),
    ('https://en.wikipedia.org/wiki/Greeneye', 'Greeneye'),
    ('https://en.wikipedia.org/wiki/Greenling', 'Greenling'),
    ('https://en.wikipedia.org/wiki/Dichotomyctere_nigroviridis', 'Dichotomyctere nigroviridis'),
    ('https://en.wikipedia.org/wiki/Ground_shark', 'Ground shark'),
    ('https://en.wikipedia.org/wiki/Grouper', 'Grouper'),
    ('https://en.wikipedia.org/wiki/Grunion', 'Grunion'),
    ('https://en.wikipedia.org/wiki/Grunter', 'Grunter'),
    ('https://en.wikipedia.org/wiki/Guitarfish', 'Guitarfish'),
    ('https://en.wikipedia.org/wiki/Gulf_menhaden', 'Gulf menhaden'),
    ('https://en.wikipedia.org/wiki/Guppy', 'Guppy'),
    ('https://en.wikipedia.org/wiki/Haddock', 'Haddock'),
    ('https://en.wikipedia.org/wiki/Hagfish', 'Hagfish'),
    ('https://en.wikipedia.org/wiki/Halfmoon', 'Halfmoon'),
    ('https://en.wikipedia.org/wiki/Halosaur', 'Halosaur'),
    ('https://en.wikipedia.org/wiki/Hammerjaw', 'Hammerjaw'),
    ('https://en.wikipedia.org/wiki/Handfish', 'Handfish'),
    ('https://en.wikipedia.org/wiki/Hawkfish', 'Hawkfish'),
    ('https://en.wikipedia.org/wiki/Herring_smelt', 'Herring smelt'),
    ('https://en.wikipedia.org/wiki/Hillstream_loach', 'Hillstream loach'),
    ('https://en.wikipedia.org/wiki/Hog_sucker', 'Hog sucker'),
    ('https://en.wikipedia.org/wiki/Horsefish', 'Horsefish'),
    ('https://en.wikipedia.org/wiki/Houndshark', 'Houndshark'),
    ('https://en.wikipedia.org/wiki/Huchen', 'Huchen'),
    ('https://en.wikipedia.org/wiki/Channichthyidae', 'Channichthyidae'),
    ('https://en.wikipedia.org/wiki/Ilish', 'Ilish'),
    ('https://en.wikipedia.org/wiki/Japanese_eel', 'Japanese eel'),
    ('https://en.wikipedia.org/wiki/Jawfish', 'Jawfish'),
    ('https://en.wikipedia.org/wiki/Jewelfish', 'Jewelfish'),
    ('https://en.wikipedia.org/wiki/Jewel_tetra', 'Jewel tetra'),
    ('https://en.wikipedia.org/wiki/John_Dory', 'John Dory'),
    ('https://en.wikipedia.org/wiki/Kafue_pike', 'Kafue pike'),
    ('https://en.wikipedia.org/wiki/Kahawai', 'Kahawai'),
    ('https://en.wikipedia.org/wiki/Kelp_perch', 'Kelp perch'),
    ('https://en.wikipedia.org/wiki/Killifish', 'Killifish'),
    ('https://en.wikipedia.org/wiki/Kissing_gourami', 'Kissing gourami'),
    ('https://en.wikipedia.org/wiki/Knifejaw', 'Knifejaw'),
    ('https://en.wikipedia.org/wiki/Koi', 'Koi'),
    ('https://en.wikipedia.org/wiki/Ladyfish', 'Ladyfish'),
    ('https://en.wikipedia.org/wiki/Lake_chub', 'Lake chub'),
    ('https://en.wikipedia.org/wiki/Lake_trout', 'Lake trout'),
    ('https://en.wikipedia.org/wiki/Lake_whitefish', 'Lake whitefish'),
    ('https://en.wikipedia.org/wiki/Lanternfish', 'Lanternfish'),
    ('https://en.wikipedia.org/wiki/Largemouth_bass', 'Largemouth bass'),
    ('https://en.wikipedia.org/wiki/Lefteye_flounder', 'Lefteye flounder'),
    ('https://en.wikipedia.org/wiki/Lemon_shark', 'Lemon shark'),
    ('https://en.wikipedia.org/wiki/Lemon_sole', 'Lemon sole'),
    ('https://en.wikipedia.org/wiki/Lemon_tetra', 'Lemon tetra'),
    ('https://en.wikipedia.org/wiki/Lenok', 'Lenok'),
    ('https://en.wikipedia.org/wiki/Leopard_danio', 'Leopard danio'),
    ('https://en.wikipedia.org/wiki/Ling_cod', 'Ling cod'),
    ('https://en.wikipedia.org/wiki/Lizardfish', 'Lizardfish'),
    ('https://en.wikipedia.org/wiki/Longfin', 'Longfin'),
    ('https://en.wikipedia.org/wiki/Longnose_dace', 'Longnose dace'),
    ('https://en.wikipedia.org/wiki/Longnose_sucker', 'Longnose sucker'),
    ('https://en.wikipedia.org/wiki/Long-whiskered_catfish', 'Long-whiskered catfish'),
    ('https://en.wikipedia.org/wiki/Lost_River_sucker', 'Lost River sucker'),
    ('https://en.wikipedia.org/wiki/Luderick', 'Luderick'),
    ('https://en.wikipedia.org/wiki/Lumpsucker', 'Lumpsucker'),
    ('https://en.wikipedia.org/wiki/Lungfish', 'Lungfish'),
    ('https://en.wikipedia.org/wiki/Mackerel_shark', 'Mackerel shark'),
    ('https://en.wikipedia.org/wiki/Mahi-mahi', 'Mahi-mahi'),
    ('https://en.wikipedia.org/wiki/Mahseer', 'Mahseer'),
    ('https://en.wikipedia.org/wiki/Mail-cheeked_fish', 'Mail-cheeked fish'),
    ('https://en.wikipedia.org/wiki/Man-of-war_fish', 'Man-of-war fish'),
    ('https://en.wikipedia.org/wiki/Manta_ray', 'Manta ray'),
    ('https://en.wikipedia.org/wiki/Marblefish', 'Marblefish'),
    ('https://en.wikipedia.org/wiki/Marlin', 'Marlin'),
    ('https://en.wikipedia.org/wiki/Medaka', 'Medaka'),
    ('https://en.wikipedia.org/wiki/Megamouth_shark', 'Megamouth shark'),
    ('https://en.wikipedia.org/wiki/Menhaden', 'Menhaden'),
    ('https://en.wikipedia.org/wiki/Midshipman_fish', 'Midshipman fish'),
    ('https://en.wikipedia.org/wiki/Milkfish', 'Milkfish'),
    ('https://en.wikipedia.org/wiki/Minnow', 'Minnow'),
    ('https://en.wikipedia.org/wiki/Mojarra', 'Mojarra'),
    ('https://en.wikipedia.org/wiki/Mola_mola', 'Mola mola'),
    ('https://en.wikipedia.org/wiki/Monkfish', 'Monkfish'),
    ('https://en.wikipedia.org/wiki/Mooneye', 'Mooneye'),
    ('https://en.wikipedia.org/wiki/Moorish_idol', 'Moorish idol'),
    ('https://en.wikipedia.org/wiki/Moray_eel', 'Moray eel'),
    ('https://en.wikipedia.org/wiki/Mosquitofish', 'Mosquitofish'),
    ('https://en.wikipedia.org/wiki/Mozambique_tilapia', 'Mozambique tilapia'),
    ('https://en.wikipedia.org/wiki/Mrigal', 'Mrigal'),
    ('https://en.wikipedia.org/wiki/Mummichog', 'Mummichog'),
    ('https://en.wikipedia.org/wiki/Murray_cod', 'Murray cod'),
    ('https://en.wikipedia.org/wiki/Muskellunge', 'Muskellunge'),
    ('https://en.wikipedia.org/wiki/Mustache_triggerfish', 'Mustache triggerfish'),
    ('https://en.wikipedia.org/wiki/Neon_tetra', 'Neon tetra'),
    ('https://en.wikipedia.org/wiki/New_World_rivuline', 'New World rivuline'),
    ('https://en.wikipedia.org/wiki/Nibble_fish', 'Nibble fish'),
    ('https://en.wikipedia.org/wiki/North_American_darter', 'North American darter'),
    ('https://en.wikipedia.org/wiki/Northern_anchovy', 'Northern anchovy'),
    ('https://en.wikipedia.org/wiki/Northern_clingfish', 'Northern clingfish'),
    ('https://en.wikipedia.org/wiki/Northern_pike', 'Northern pike'),
    ('https://en.wikipedia.org/wiki/Northern_squawfish', 'Northern squawfish'),
    ('https://en.wikipedia.org/wiki/Northern_stargazer', 'Northern stargazer'),
    ('https://en.wikipedia.org/wiki/Nototheniidae', 'Nototheniidae'),
    ('https://en.wikipedia.org/wiki/Oceanic_whitetip_shark', 'Oceanic whitetip shark'),
    ('https://en.wikipedia.org/wiki/Oilfish', 'Oilfish'),
    ('https://en.wikipedia.org/wiki/Oldwife', 'Oldwife'),
    ('https://en.wikipedia.org/wiki/Old_World_knifefish', 'Old World knifefish'),
    ('https://en.wikipedia.org/wiki/Olive_flounder', 'Olive flounder'),
    ('https://en.wikipedia.org/wiki/Opah', 'Opah'),
    ('https://en.wikipedia.org/wiki/Opaleye', 'Opaleye'),
    ('https://en.wikipedia.org/wiki/Orangespine_unicorn_fish', 'Orangespine unicorn fish'),
    ('https://en.wikipedia.org/wiki/Orangestriped_triggerfish', 'Orangestriped triggerfish'),
    ('https://en.wikipedia.org/wiki/Orbicular_batfish', 'Orbicular batfish'),
    ('https://en.wikipedia.org/wiki/Oregon_chub', 'Oregon chub'),
    ('https://en.wikipedia.org/wiki/Orfe', 'Orfe'),
    ('https://en.wikipedia.org/wiki/Oriental_loach', 'Oriental loach'),
    ('https://en.wikipedia.org/wiki/Owens_pupfish', 'Owens pupfish'),
    ('https://en.wikipedia.org/wiki/Pacific_rudderfish', 'Pacific rudderfish'),
    ('https://en.wikipedia.org/wiki/Pacific_salmon', 'Pacific salmon'),
    ('https://en.wikipedia.org/wiki/Paddlefish', 'Paddlefish'),
    ('https://en.wikipedia.org/wiki/Iridescent_shark', 'Iridescent shark'),
    ('https://en.wikipedia.org/wiki/Paradise_fish', 'Paradise fish'),
    ('https://en.wikipedia.org/wiki/Parore', 'Parore'),
    ('https://en.wikipedia.org/wiki/Parrotfish', 'Parrotfish'),
    ('https://en.wikipedia.org/wiki/Peamouth', 'Peamouth'),
    ('https://en.wikipedia.org/wiki/Pearl_danio', 'Pearl danio'),
    ('https://en.wikipedia.org/wiki/Pearl_perch', 'Pearl perch'),
    ('https://en.wikipedia.org/wiki/Pencilfish', 'Pencilfish'),
    ('https://en.wikipedia.org/wiki/Peppered_corydoras', 'Peppered corydoras'),
    ('https://en.wikipedia.org/wiki/Perch', 'Perch'),
    ('https://en.wikipedia.org/wiki/Peters%27_elephantnose_fish', 'Peters'' elephantnose fish'),
    ('https://en.wikipedia.org/wiki/Pilot_fish', 'Pilot fish'),
    ('https://en.wikipedia.org/wiki/Pineapplefish', 'Pineapplefish'),
    ('https://en.wikipedia.org/wiki/Pink_salmon', 'Pink salmon'),
    ('https://en.wikipedia.org/wiki/P%C3%ADntano', 'P ntano'),
    ('https://en.wikipedia.org/wiki/Piranha', 'Piranha'),
    ('https://en.wikipedia.org/wiki/Pirarucu', 'Pirarucu'),
    ('https://en.wikipedia.org/wiki/Pirate_perch', 'Pirate perch'),
    ('https://en.wikipedia.org/wiki/Pollyfish', 'Pollyfish'),
    ('https://en.wikipedia.org/wiki/Pollock', 'Pollock'),
    ('https://en.wikipedia.org/wiki/Pompano_dolphinfish', 'Pompano dolphinfish'),
    ('https://en.wikipedia.org/wiki/Popeye_catalufa', 'Popeye catalufa'),
    ('https://en.wikipedia.org/wiki/Porcupinefish', 'Porcupinefish'),
    ('https://en.wikipedia.org/wiki/Pumpkinseed', 'Pumpkinseed'),
    ('https://en.wikipedia.org/wiki/Pupfish', 'Pupfish'),
    ('https://en.wikipedia.org/wiki/Pygmy_sunfish', 'Pygmy sunfish'),
    ('https://en.wikipedia.org/wiki/Queen_parrotfish', 'Queen parrotfish'),
    ('https://en.wikipedia.org/wiki/Queen_triggerfish', 'Queen triggerfish'),
    ('https://en.wikipedia.org/wiki/Quillback', 'Quillback'),
    ('https://en.wikipedia.org/wiki/Rabbitfish', 'Rabbitfish'),
    ('https://en.wikipedia.org/wiki/Raccoon_butterfly_fish', 'Raccoon butterfly fish'),
    ('https://en.wikipedia.org/wiki/Rainbow_trout', 'Rainbow trout'),
    ('https://en.wikipedia.org/wiki/Rainbowfish', 'Rainbowfish'),
    ('https://en.wikipedia.org/wiki/Rasbora', 'Rasbora'),
    ('https://en.wikipedia.org/wiki/Batoidea', 'Batoidea'),
    ('https://en.wikipedia.org/wiki/Red_grouper', 'Red grouper'),
    ('https://en.wikipedia.org/wiki/Red_salmon', 'Red salmon'),
    ('https://en.wikipedia.org/wiki/Redfin_perch', 'Redfin perch'),
    ('https://en.wikipedia.org/wiki/Redfish', 'Redfish'),
    ('https://en.wikipedia.org/wiki/Redlip_blenny', 'Redlip blenny'),
    ('https://en.wikipedia.org/wiki/Remora', 'Remora'),
    ('https://en.wikipedia.org/wiki/Requiem_shark', 'Requiem shark'),
    ('https://en.wikipedia.org/wiki/Ribbon_eel', 'Ribbon eel'),
    ('https://en.wikipedia.org/wiki/Ricefish', 'Ricefish'),
    ('https://en.wikipedia.org/wiki/Rio_Grande_perch', 'Rio Grande perch'),
    ('https://en.wikipedia.org/wiki/River_loach', 'River loach'),
    ('https://en.wikipedia.org/wiki/River_shark', 'River shark'),
    ('https://en.wikipedia.org/wiki/River_stingray', 'River stingray'),
    ('https://en.wikipedia.org/wiki/Roanoke_bass', 'Roanoke bass'),
    ('https://en.wikipedia.org/wiki/Rock_beauty', 'Rock beauty'),
    ('https://en.wikipedia.org/wiki/Rough_scad', 'Rough scad'),
    ('https://en.wikipedia.org/wiki/Round_stingray', 'Round stingray'),
    ('https://en.wikipedia.org/wiki/Round_whitefish', 'Round whitefish'),
    ('https://en.wikipedia.org/wiki/Rudd', 'Rudd'),
    ('https://en.wikipedia.org/wiki/Ruffe', 'Ruffe'),
    ('https://en.wikipedia.org/wiki/Russian_sturgeon', 'Russian sturgeon'),
    ('https://en.wikipedia.org/wiki/Saber-toothed_blenny', 'Saber-toothed blenny'),
    ('https://en.wikipedia.org/wiki/Sablefish', 'Sablefish'),
    ('https://en.wikipedia.org/wiki/Stromateidae', 'Stromateidae'),
    ('https://en.wikipedia.org/wiki/Sailfin_silverside', 'Sailfin silverside'),
    ('https://en.wikipedia.org/wiki/Sailfish', 'Sailfish'),
    ('https://en.wikipedia.org/wiki/Salmon', 'Salmon'),
    ('https://en.wikipedia.org/wiki/Sandbar_shark', 'Sandbar shark'),
    ('https://en.wikipedia.org/wiki/Sand_lance', 'Sand lance'),
    ('https://en.wikipedia.org/wiki/Sandperch', 'Sandperch'),
    ('https://en.wikipedia.org/wiki/Sand_tiger', 'Sand tiger'),
    ('https://en.wikipedia.org/wiki/Sand_tilefish', 'Sand tilefish'),
    ('https://en.wikipedia.org/wiki/Scup', 'Scup'),
    ('https://en.wikipedia.org/wiki/Sea_bream', 'Sea bream'),
    ('https://en.wikipedia.org/wiki/Sea_chub', 'Sea chub'),
    ('https://en.wikipedia.org/wiki/Snailfish', 'Snailfish'),
    ('https://en.wikipedia.org/wiki/Sea_toad', 'Sea toad'),
    ('https://en.wikipedia.org/wiki/Seahorse', 'Seahorse'),
    ('https://en.wikipedia.org/wiki/Searobin', 'Searobin'),
    ('https://en.wikipedia.org/wiki/Shad', 'Shad'),
    ('https://en.wikipedia.org/wiki/Sharpnose_puffer', 'Sharpnose puffer'),
    ('https://en.wikipedia.org/wiki/Sheepshead_minnow', 'Sheepshead minnow'),
    ('https://en.wikipedia.org/wiki/Siamese_fighting_fish', 'Siamese fighting fish'),
    ('https://en.wikipedia.org/wiki/Sillago', 'Sillago'),
    ('https://en.wikipedia.org/wiki/Silver_carp', 'Silver carp'),
    ('https://en.wikipedia.org/wiki/Silvertip_tetra', 'Silvertip tetra'),
    ('https://en.wikipedia.org/wiki/Sixgill_ray', 'Sixgill ray'),
    ('https://en.wikipedia.org/wiki/Skilfish', 'Skilfish'),
    ('https://en.wikipedia.org/wiki/Sleeper_shark', 'Sleeper shark'),
    ('https://en.wikipedia.org/wiki/Slimy_sculpin', 'Slimy sculpin'),
    ('https://en.wikipedia.org/wiki/Smalltooth_sawfish', 'Smalltooth sawfish'),
    ('https://en.wikipedia.org/wiki/Smelt-whiting', 'Smelt-whiting'),
    ('https://en.wikipedia.org/wiki/Smooth_dogfish', 'Smooth dogfish'),
    ('https://en.wikipedia.org/wiki/Snipefish', 'Snipefish'),
    ('https://en.wikipedia.org/wiki/Soldierfish', 'Soldierfish'),
    ('https://en.wikipedia.org/wiki/Spadefish', 'Spadefish'),
    ('https://en.wikipedia.org/wiki/Spiderfish', 'Spiderfish'),
    ('https://en.wikipedia.org/wiki/Spikefish', 'Spikefish'),
    ('https://en.wikipedia.org/wiki/Spinefoot', 'Spinefoot'),
    ('https://en.wikipedia.org/wiki/Spiny_basslet', 'Spiny basslet'),
    ('https://en.wikipedia.org/wiki/Spiny_dogfish', 'Spiny dogfish'),
    ('https://en.wikipedia.org/wiki/Splitfin', 'Splitfin'),
    ('https://en.wikipedia.org/wiki/Spotted_climbing_perch', 'Spotted climbing perch'),
    ('https://en.wikipedia.org/wiki/Spottail_pinfish', 'Spottail pinfish'),
    ('https://en.wikipedia.org/wiki/Stingray', 'Stingray'),
    ('https://en.wikipedia.org/wiki/Stoneroller_minnow', 'Stoneroller minnow'),
    ('https://en.wikipedia.org/wiki/Stream_catfish', 'Stream catfish'),
    ('https://en.wikipedia.org/wiki/Striped_bass', 'Striped bass'),
    ('https://en.wikipedia.org/wiki/Catostomidae', 'Catostomidae'),
    ('https://en.wikipedia.org/wiki/Surfperch', 'Surfperch'),
    ('https://en.wikipedia.org/wiki/Surgeonfish', 'Surgeonfish'),
    ('https://en.wikipedia.org/wiki/Sweeper', 'Sweeper'),
    ('https://en.wikipedia.org/wiki/Swordfish', 'Swordfish'),
    ('https://en.wikipedia.org/wiki/Swordtail', 'Swordtail'),
    ('https://en.wikipedia.org/wiki/Tadpole_cod', 'Tadpole cod'),
    ('https://en.wikipedia.org/wiki/Tarpon', 'Tarpon'),
    ('https://en.wikipedia.org/wiki/Tarwhine', 'Tarwhine'),
    ('https://en.wikipedia.org/wiki/Temperate_bass', 'Temperate bass'),
    ('https://en.wikipedia.org/wiki/Tench', 'Tench'),
    ('https://en.wikipedia.org/wiki/Tenpounder', 'Tenpounder'),
    ('https://en.wikipedia.org/wiki/Tetra', 'Tetra'),
    ('https://en.wikipedia.org/wiki/Threadfin', 'Threadfin'),
    ('https://en.wikipedia.org/wiki/Threadfin_bream', 'Threadfin bream'),
    ('https://en.wikipedia.org/wiki/Three_spot_gourami', 'Three spot gourami'),
    ('https://en.wikipedia.org/wiki/Three-toothed_puffer', 'Three-toothed puffer'),
    ('https://en.wikipedia.org/wiki/Thresher_shark', 'Thresher shark'),
    ('https://en.wikipedia.org/wiki/Tiger_barb', 'Tiger barb'),
    ('https://en.wikipedia.org/wiki/Tigerperch', 'Tigerperch'),
    ('https://en.wikipedia.org/wiki/Tiger_shark', 'Tiger shark'),
    ('https://en.wikipedia.org/wiki/Tiger_shovelnose_catfish', 'Tiger shovelnose catfish'),
    ('https://en.wikipedia.org/wiki/Tilefish', 'Tilefish'),
    ('https://en.wikipedia.org/wiki/Titan_triggerfish', 'Titan triggerfish'),
    ('https://en.wikipedia.org/wiki/Tommy_ruff', 'Tommy ruff'),
    ('https://en.wikipedia.org/wiki/Tompot_blenny', 'Tompot blenny'),
    ('https://en.wikipedia.org/wiki/Topminnow', 'Topminnow'),
    ('https://en.wikipedia.org/wiki/Trahira', 'Trahira'),
    ('https://en.wikipedia.org/wiki/Treefish', 'Treefish'),
    ('https://en.wikipedia.org/wiki/Trevally', 'Trevally'),
    ('https://en.wikipedia.org/wiki/Triggerfish', 'Triggerfish'),
    ('https://en.wikipedia.org/wiki/Triplefin_blenny', 'Triplefin blenny'),
    ('https://en.wikipedia.org/wiki/Triplespine', 'Triplespine'),
    ('https://en.wikipedia.org/wiki/Turbot', 'Turbot'),
    ('https://en.wikipedia.org/wiki/Two_spotted_goby', 'Two spotted goby'),
    ('https://en.wikipedia.org/wiki/Velvet_catfish', 'Velvet catfish'),
    ('https://en.wikipedia.org/wiki/Vimba', 'Vimba'),
    ('https://en.wikipedia.org/wiki/Viperfish', 'Viperfish'),
    ('https://en.wikipedia.org/wiki/Wahoo', 'Wahoo'),
    ('https://en.wikipedia.org/wiki/Wallago', 'Wallago'),
    ('https://en.wikipedia.org/wiki/Walleye', 'Walleye'),
    ('https://en.wikipedia.org/wiki/Walleye_pollock', 'Walleye pollock'),
    ('https://en.wikipedia.org/wiki/Escolar', 'Escolar'),
    ('https://en.wikipedia.org/wiki/Warmouth', 'Warmouth'),
    ('https://en.wikipedia.org/wiki/Waspfish', 'Waspfish'),
    ('https://en.wikipedia.org/wiki/Weever', 'Weever'),
    ('https://en.wikipedia.org/wiki/Weeverfish', 'Weeverfish'),
    ('https://en.wikipedia.org/wiki/Whale_shark', 'Whale shark'),
    ('https://en.wikipedia.org/wiki/Whitebait', 'Whitebait'),
    ('https://en.wikipedia.org/wiki/White_croaker', 'White croaker'),
    ('https://en.wikipedia.org/wiki/White_marlin', 'White marlin'),
    ('https://en.wikipedia.org/wiki/White_shark', 'White shark'),
    ('https://en.wikipedia.org/wiki/Whitetip_reef_shark', 'Whitetip reef shark'),
    ('https://en.wikipedia.org/wiki/Wolf-eel', 'Wolf-eel'),
    ('https://en.wikipedia.org/wiki/Wolf-herring', 'Wolf-herring'),
    ('https://en.wikipedia.org/wiki/Wrasse', 'Wrasse'),
    ('https://en.wikipedia.org/wiki/X-ray_tetra', 'X-ray tetra'),
    ('https://en.wikipedia.org/wiki/Yellow-and-black_triplefin', 'Yellow-and-black triplefin'),
    ('https://en.wikipedia.org/wiki/Yellowback_fusilier', 'Yellowback fusilier'),
    ('https://en.wikipedia.org/wiki/Yellowbanded_perch', 'Yellowbanded perch'),
    ('https://en.wikipedia.org/wiki/Yellow_bass', 'Yellow bass'),
    ('https://en.wikipedia.org/wiki/Yellowedge_grouper', 'Yellowedge grouper'),
    ('https://en.wikipedia.org/wiki/Yellow-edged_moray', 'Yellow-edged moray'),
    ('https://en.wikipedia.org/wiki/White_shark', 'White shark'),
    ('https://en.wikipedia.org/wiki/Whitetip_reef_shark', 'Whitetip reef shark'),
    ('https://en.wikipedia.org/wiki/Wolf-eel', 'Wolf-eel'),
    ('https://en.wikipedia.org/wiki/Wolf-herring', 'Wolf-herring'),
    ('https://en.wikipedia.org/wiki/Wrasse', 'Wrasse'),
    ('https://en.wikipedia.org/wiki/X-ray_tetra', 'X-ray tetra'),
    ('https://en.wikipedia.org/wiki/Yellow-and-black_triplefin', 'Yellow-and-black triplefin'),
    ('https://en.wikipedia.org/wiki/Yellowback_fusilier', 'Yellowback fusilier'),
    ('https://en.wikipedia.org/wiki/Yellowbanded_perch', 'Yellowbanded perch'),
    ('https://en.wikipedia.org/wiki/Yellow_bass', 'Yellow bass'),
    ('https://en.wikipedia.org/wiki/Yellowedge_grouper', 'Yellowedge grouper'),
    ('https://en.wikipedia.org/wiki/Yellow-edged_moray', 'Yellow-edged moray'),
    ('https://en.wikipedia.org/wiki/Yellowfin_croaker', 'Yellowfin croaker'),
    ('https://en.wikipedia.org/wiki/Yellowfin_cutthroat_trout', 'Yellowfin cutthroat trout'),
    ('https://en.wikipedia.org/wiki/Yellowfin_grouper', 'Yellowfin grouper'),
    ('https://en.wikipedia.org/wiki/Yellowfin_tuna', 'Yellowfin tuna'),
    ('https://en.wikipedia.org/wiki/Yellowfin_surgeonfish', 'Yellowfin surgeonfish')
ON CONFLICT (wiki_url) DO NOTHING;
